### ISSUE TITLE
Year on year growth calculation

### ISSUE THREAD

**Issue by DomitienAdW** [DomitienAdW/Harfang#126]
The correct year on year growth calculation should be: current year cumulated / last year cumulated
It should be displayed with a "+" or "-".

/!\ In the last version of the monthly report show I have slightly moved this data in the html.
check to correct it in the proper version ;) 

![image](https://user-images.githubusercontent.com/26465528/36385976-919b7cd6-1594-11e8-8ce4-c563a7e6ded9.png)

**Comment by nfilzi** [comment]
Can you detail precisely the computation you need here?

**Comment by DomitienAdW** [comment]
#CurrentYearData ) / #LastYearData

in % and with a "+" or "-"
