### ISSUE TITLE
add a warning on campaign with data problem

### ISSUE THREAD

**Issue by DomitienAdW** [DomitienAdW/Harfang#131]
partial exist under the name _bug_banner.html.erb

**Comment by DomitienAdW** [comment]
![image](https://user-images.githubusercontent.com/26465528/36548457-a921785c-17f0-11e8-83ff-7c1ec855dd9c.png)

**Comment by DomitienAdW** [comment]
et sur les reports

![image](https://user-images.githubusercontent.com/26465528/36548595-04dc3b46-17f1-11e8-9f04-075acefc235a.png)

**Comment by nfilzi** [comment]
This should be paired with a user facing feature to file bugs of certain natures on both campaigns & monthly reports. Then we could use this information to display the matching banner, with a more useful message than a generic one. WDYT @DomitienAdW ?

**Comment by nfilzi** [comment]
@DomitienAdW In lot 3 ?

**Comment by nfilzi** [comment]
IMO this should belong to a later lot, because of the need for a user facing feature for bugs reporting.

**Comment by DomitienAdW** [comment]
I totally agree for the new campaign / new bug but IMO those banners can already be included in all the old campaign (before june 2017) and old report (before december 2013).

**Comment by nfilzi** [comment]
Alright! I'm adding this to my lot 3 finishing tasks.

**Comment by nfilzi** [comment]
Fixed in #176
