### ISSUE TITLE
pb in data on campaign #1973

### ISSUE THREAD

**Issue by DomitienAdW** [DomitienAdW/Harfang#140]
a new pledge level has been created on the 12/12.

on the daily backer data report those new data this data is at the beggining of the campaign 

![image](https://user-images.githubusercontent.com/26465528/36674968-f4975238-1b07-11e8-899d-9a3cfb5f3944.png)

**Comment by DomitienAdW** [comment]
same problem on #9124

**Comment by nfilzi** [comment]
Now we have this layout for the data:
<img width="963" alt="screen shot 2018-03-11 at 01 25 37" src="https://user-images.githubusercontent.com/7533706/37248194-23cab0a0-24cb-11e8-941f-b55334636e2b.png">

By default, backers count will be at 0 for days before pledges starting during the campaign are introduced.

**Comment by DomitienAdW** [comment]
It as creat a new pb on campaign such as #9124

**Comment by nfilzi** [comment]
Fixed with #180

**Comment by DomitienAdW** [comment]
aaaaannnnd it broke the general data graph :D 

![image](https://user-images.githubusercontent.com/26465528/37511622-d383be50-28ff-11e8-8d10-bbd8aff618fb.png)

**Comment by nfilzi** [comment]
aha it did not break it, it made sth appear. 
On this day, the daily report background job failed to launch subsequent pledge_daily_reports jobs.

So when the no reward pledge daily report was created for this day, it got all the backers count for itself.
Then the next day everything worked again, so we got correct numbers back 😅

**Comment by nfilzi** [comment]
And I think sth also happened on the `Core Box` pledge daily report scraping, it falls to zero on the last day, coming from ~13000 the day before.
