### ISSUE TITLE
add new column in monthly report export

### ISSUE THREAD

**Issue by DomitienAdW** [DomitienAdW/Harfang#146]
The monthly report should include:
- BGG link
- start date
- end date
- amount pledged (last day)
- nb of backer (last day)

Exept for the BGG link, these new columns should not be updated during import

**Comment by nfilzi** [comment]
Alright 👌

**Comment by nfilzi** [comment]
Done partly in #162, on the exporting side.
Working on the importing side today in branch `improve/campaigns/bulk-import-from-csv`.
