### ISSUE TITLE
add project data on front

### ISSUE THREAD

**Issue by DomitienAdW** [DomitienAdW/Harfang#147]
In the "product detail" tab on campaign pages most data displayed (BGG categories, designer…) are not linked to backend :D

Can you also add the other product data (BGG weight…) in an HTML comment.
I'll display them properly later ;)

**Comment by nfilzi** [comment]
The data should already be loaded in the HTML. Give me one campaign id where you think it's not, I'll check then.

**Comment by DomitienAdW** [comment]
#215

**Comment by nfilzi** [comment]
On the product bgg stats part:

![screen shot 2018-03-01 at 15 34 30](https://user-images.githubusercontent.com/7533706/36850140-3de8ea22-1d66-11e8-8479-74332a25083e.png)

**Comment by DomitienAdW** [comment]
Very nice!
