### ISSUE TITLE
BGG data : duration pb

### ISSUE THREAD

**Issue by DomitienAdW** [DomitienAdW/Harfang#149]
On some BGG project duration only have one value.
In that case it is dispalyed on harfang : #value - 0 instaed of #value - $value

I see that on #215 but corrected it before thinking you would have wanted to see it :D

**Comment by nfilzi** [comment]
Not an issue on my end, look at the BGG API response, at the `<maxplaytime>` xml key: https://boardgamegeek.com/xmlapi/boardgame/224710?stats=1

**Comment by DomitienAdW** [comment]
f***

if we could not trust BGG… :'D
