### ISSUE TITLE
update Monthly report

### ISSUE THREAD

**Issue by DomitienAdW** [DomitienAdW/Harfang#153]
- [x] top 12 by category
- [x] change cumulative graphs to normal graphs

**Comment by nfilzi** [comment]
@DomitienAdW you also told me that cumulative graphs should not be cumulative anymore, if I recall correctly. Can you detail your need again here?

**Comment by DomitienAdW** [comment]
I was talking of the 3 graph on top of the monthly report pages:
- Successfully funded projects
- Number of backers
- Collected funds

They should display for each mounth the raw data instead of cumulated them on a rolling year.

**Comment by nfilzi** [comment]
Fixed in #190
