### ISSUE TITLE
reward tiers missing…

### ISSUE THREAD

**Issue by DomitienAdW** [DomitienAdW/Harfang#157]
In our « evolution of the backer number we are missing the « no reward selected » tiers…

**Comment by nfilzi** [comment]
Dude, I asked you when I was scraping it, and you told me to not bother with it 😭
So the data is just not there at all.

**Comment by DomitienAdW** [comment]
man… we have it…

**Comment by nfilzi** [comment]
what?!

**Comment by DomitienAdW** [comment]
#DailyBackerData - ( SumOfAll #DailyRewardTiers ) = #DailyNoRewardBackers

**Comment by DomitienAdW** [comment]
:P

**Comment by DomitienAdW** [comment]
if you prefer we can display the #dailyBackerNumber on this graph ;)

**Comment by nfilzi** [comment]
I'll look into it.

**Comment by nfilzi** [comment]
Fixed in #179
