### ISSUE TITLE
Switching between scopes on campaigns/index

### ISSUE THREAD

**Issue by nfilzi** [DomitienAdW/Harfang#17]
- Latest
- Most funded
- Most backed
- Closing soon
@DomitienAdW Those were all the options?

**Comment by DomitienAdW** [comment]
Yes, it is!

There will also be filter directly on the table (less/more than X backers, funded/not funded/ % of fund, open/ended, category, mechanism, topic). It was on the design I send you but can be in a further version.

**Comment by DomitienAdW** [comment]
Correction:
The option should be 
- all,
- live,
- funded,
- not funded

_(message on slack on june 15th)_

**Comment by nfilzi** [comment]
Scopes fixed in #116
