### ISSUE TITLE
add js to display filter on campaign list

### ISSUE THREAD

**Issue by DomitienAdW** [DomitienAdW/Harfang#185]
On campaign list, when the filter icon is clicked the `.filter` class should be remove from the div just below and add again on a new click on the icon.

btw if you can change the icon to `iconClose.svg` it will be even better

**Comment by nfilzi** [comment]
Just to make sure I understood correctly:
When the user clicks on the filter icon, the advanced search menu should appear, and the icon should be replaced with the close one?

**Comment by DomitienAdW** [comment]
correct
