### ISSUE TITLE
monthly report : year comparison

### ISSUE THREAD

**Issue by DomitienAdW** [DomitienAdW/Harfang#191]
The year comparison on funded projet/backers/fund should display only 12 value

**Comment by nfilzi** [comment]
Are you sure? I recall at some point you wanted to also have the value from last year same month?

**Comment by DomitienAdW** [comment]
At the moment there is 14 wich make no sens :D 
and as of today I think 12 values will be better ;)

**Comment by nfilzi** [comment]
Alright, 12 it is then. 
On the 14 values part, it's a bug, and it's only happening with Feburary reports, and I can't figure out why 😅
