### ISSUE TITLE
Front modification - Campaign list

### ISSUE THREAD

**Issue by DomitienAdW** [DomitienAdW/Harfang#50]
- [x] fix mechanism editing
- [x] change pledge color depanding on the % 
- 0-50: red
- 50-100: orange
- more than 100: green

- [x] change ending date color depending on the current day
- more than 7 day left: green 
- 2 to 7 day left: orange
- 1 or 2 day left: red
- after campaign end: grey

Moved to lot-2: Topic editing

**Comment by nfilzi** [comment]
- [] Numbers to display following english notation with commas between thousands, and a point separating the decimals.

**Comment by nfilzi** [comment]
- [ ] Rounding to two decimal all percentage rates on `monthly_reports#show`
