### ISSUE TITLE
Boucle infinie lorsqu'une campagne est renommée par son créateur

### ISSUE THREAD

**Issue by DomitienAdW** [DomitienAdW/Harfang#63]
erreur 404 sur Campaigns::FetchNewCampaignsJob@new_campaigns_scrapers 

Location
----------------
app/services/campaigns/scrapers/kickstarter/get_new_campaigns_data_service.rb:29 - get_campaigns_attributes

Comment passer au dessus et éviter les retry ?

**Comment by nfilzi** [comment]
En fait, entre le moment où on a scrape pour la première fois une certaine campagne, qui sera la dernière loadé la fois précédente,  et la fois où on va chercher à load les campagnes depuis cette dernière campagne, les mecs derrière la campagne ont changé le nom de la campagne, ce qui laisse mon code pris dans une boucle infinie à tenter de trouver un match exact entre le nom de la dernière campagne en BDD et une de celles renvoyées par l’API de kickstarter.

Du coup on arrive dans la page 100+ renvoyées par l’API, et à un moment, bah y a plus de page dispo, d’où la 404

Solution: sauver dans notre BDD les ids Kickstarter, et le match se fera maintenant là-dessus, plutôt que sur un nom potentiellement changeant.
